#!/bin/bash

defaultmodel=$(dirname $0)/allamas_sorted_by_size.txt

source $(dirname $0)/echo_formatted.sh

echo_usage() {
  echo "Usage: ai [replay | repeat | save] [<prompt>] [<model> (default: $defaultmodel)]"
}

# test whether at least one argument (the prompt) is provided
if [ $# -lt 1 ]; then
  echo_usage
  exit 1
fi

prompt=$1

save_prompt() {
  if ! grep -Fq "$1"     $2; then
    echo   -e "\n$1" >>  $2
    echo_italics "(new prompt added to $2)" >&2
  else
    echo_italics "(prompt already in $2)"   >&2
  fi
}

if [ "$prompt" == "save" ]; then # take last prompt from ai-prompts.txt
  prompt="$(tail -n1 ai-prompts.txt)"
  if [ -z "$prompt" ]; then
    echo -e "\e[31mno previous prompt found in ai-prompts.txt\e[0m\n" >&2
    exit 1
  fi
  save_prompt "$prompt" $(dirname $0)/ai-prompts-curated.txt
  exit 0
fi

if [ "$prompt" == "repeat" ]; then # take last prompt from ai-prompts.txt
  prompt="$(tail -n1 ai-prompts.txt)"
  if [ -z "$prompt" ]; then
    echo -e "\e[31mno previous prompt found in ai-prompts.txt\e[0m\n" >&2
    exit 1
  fi
  isreplay=true
fi

if [ "$prompt" == "replay" ]; then # lookup the actual prompt in the curated list
  shift
  if [ $# -lt 1 ]; then # test whether the prompt keyword is provided
    echo_usage
    echo "          ( missing prompt keyword after 'replay' )"
    exit 1
  fi
  keyword=$1
  prompt="$(grep $keyword $(dirname $0)/ai-prompts-curated.txt)"
  if [ -z "$prompt" ]; then
    prompt="$(grep $keyword ai-prompts.txt)"
    if [ -z "$prompt" ]; then
      echo -e "\e[31mKeyword '$keyword' not found in ai-prompts[-curated].txt\e[0m\n" >&2
      exit 1
    else
      echo_italics 'found in ai-prompts.txt\n'
    fi
  fi
  isreplay=true
fi

model=$2
if [ -z "$model" ]; then
  model=$defaultmodel
fi

# add the prompt to the prompts file ONLY if it wasn't already there
# and if we are not in replay mode alredy
if [ -z "$isreplay" ]; then
  save_prompt "$prompt" ai-prompts.txt
else
  echo_italics "ai \"$prompt\" $model"
fi

ai_run_one() {
  defaultmodel=tinyllama

  # test whether at least one argument is provided
  if [ $# -lt 1 ]; then
    echo "Usage: ai <prompt> [<modelname>|<modelfile> (default: $defaultmodel)]"
    exit 1
  fi

  prompt=$1

  model=$2
  if [ -z "$model" ]; then
    model=$defaultmodel
  fi

  if [[ $model == gpt* ]]; then
    provider="openai-run"
  else
    provider="ollama-run"
  fi

  echo ________________________________
  echo_italics "$provider $model"

  $provider $model "$prompt"
}

echo # blank line to separate responses from the command line

if [ -f "$model" ]; then

  models=$model

  while read model; do ai_run_one "$prompt" $model; done < $models

else # $model is not a file but a specific model name

                       ai_run_one "$prompt" $model

fi # end if $model is a file

# BONUS: ANSI escape codes for text formatting
# 30	Black
# 31	Red
# 32	Green
# 33	Yellow
# 34	Blue
# 35	Magenta
# 36	Cyan
# 37	White
# 90	Bright Black
# 91	Bright Red
# 92	Bright Green
# 93	Bright Yellow
# 94	Bright Blue
# 95	Bright Magenta
# 96	Bright Cyan
# 97	Bright White
# 39	Default foreground color
# 49	Default background color
# 38;5;0 to 38;5;255	256-color mode foreground color
# 48;5;0 to 48;5;255	256-color mode background color
# 38;2;R;G;B to 38;2;R;G;B	True color foreground color
# 48;2;R;G;B to 48;2;R;G;B	True color background color
# 0	Reset / Normal
# 1	Bold or increased intensity
# 2	Faint (decreased intensity)
# 3	Italic
# 4	Underline
